remote_theme: pmarsceill/just-the-docs
lang: ja
title: Just The Docs
description: GitHub Pages Just The Docs テーマ
#logo: "/assets/images/just-the-docs.png"
search_enabled: true
aux_links:
  "GitHub ソース":
    - "https://github.com/dominowork/just-the-docs"
footer_content: 
ga_tracking: 

plugins:
  - jekyll-sitemap
